
# Staging environment variables for both FE and BE
env_name: staging
project_name: takeda-hng-portal

# Frontend
fe_repo: git@github.com:hngprojects/hng-portal-FE.git
fe_branch: staging
fe_domain: staging.takeda.emerj.net
fe_app_dir: /home/bimbo/hng-portal-FE
fe_component: frontend

# Backend
be_repo: git@github.com:hngprojects/HNG-Portal-BE.git
be_branch: staging
be_domain: api.staging.takeda.emerj.net
be_domain: api.takeda.emerj.net
be_app_dir: /home/bimbo/HNG-Portal-BE
be_component: backend

# Common
secrets_file: "{{ playbook_dir }}/secrets/staging.env"



