dev_deploy_key: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          61653236633165633331383662623466653439353433633935336532373965333864356433323531
          6436643161653538646236333231316631633931666237330a653630663063326635333936656265
          63623261373239666332353132386230623838363462353363353836333339383565636634323761
          3038393038353635620a633938363434376364626435616134316638653131613934356533386434
          30623566623966363234376636336638376661333765326437623135373730316134346332613134
          66386631323966616332306337373732636339653863396133626431363665656532306330326565
          39343534633635633934346139613338376532333332663966303437363433316539303263623635
          61396638333639643864636335356361303465313465643866396335323032656232323335376662
          61633636343935656334326334633838666130646335656364613363353730313338653832646236
          37383366626239636430303761333732373432616134306434636533633765313361323062376535
          31366337666263646165616335656362323064616536653630393939396334386264386435653764
          32343033653661383763356530646138353032336439633130313866623761663066646137316531
          34666637336563623064383537323537376366303931333934366264336533336165386266373832
          38393361666661363536306437316632626166386436306136643862653432613339623537373937
          36316132373562636562353662316639653836353961333730616465326536373439383936643136
          38613731373264393565363237613039636135656462633064613533646236356536386339306465
          33633632663038623566656361626135333863623539623565666534386165626462306438323931
          66353933386663653337386265333532383462613665396362366230373363396533386463653834
          39383632633662646261346530643434303935386232336635633837613733396435353937386365
          37343435656136383335313963646230656435363235623234306236373938383264623366353465
          35353232396330613536663638643262356463366631656663666264613435633732326563386162
          62356364653662306335656363303664646632303836306531346238323433356462663163373839
          37383333623966653663663136613436343232666236643836643335396334386364386164643332
          37353738633832626463376364633561366463376161623735613964373362643234346464643365
          65613862313132326435393032383033303965386435306566366266306535666437623435613234
          61346266633162633436343865623663663763643862653839663230663361613465363664363836
          63306163656135353565383030343339373864623364636531386437376233323364393431346638
          62303466653732386661346338616531343335333162383063643538333238663437383332646639
          64353266663433653231336530356262376662373139326230333062646361373539356465643835
          36346166376564333862633863396336646139336666393838373031323536373138656638326238
          66656161623739663136663038393035663332633337306630653261363937633730333235376539
          34613039613130353930323462623435336539303964303165326536366339383361306434633061
          38636435633265343666653232623864373066336336306464393536633961383035653965366135
          61663636333437663566343666643562626634666466366665346264346530336262363363373936
          64376632396634363039313136393831373161613333393265363363356633396465623732343732
          35666537363766353165383934313834623464363232343262333338646333323237646363393266
          62363364336630666134643938646633383832636566633065613831313933636433356262323630
          38633232343462666337646438653034633435353963666337356237643532646533636666643638
          33656232323134346231633432663538636635663762656262636666643630373938643939626338
          37373434346433666537366339373462313137363236623262643364383561303464336334356636
          34616565343465376335393234323333333930633037353763306339386265613366376161653263
          61363962663164323761353635326135326362323439393833613065326437363966633534383766
          34313162353538386162313162663731323937623833393066316266336630373537363433643434
          30376638633333373963336332663230323161333963616463666664386133383236666139663538
          31663864613136303530333937323362303235636162613362613937656235663464396130613430
          30666335303566373939636430393238373463653535613061343130666365326561666639323063
          63633735366331323738376339303338343466653063643564666165326463653036333439386436
          32373836663662356333663738383562333562343236336235376131623764303835636135353437
          32363836396131653464333262343162373836343135386537653362323737663035393039376166
          31663536653763373835646431646130633236376461636662306666376166373532623638336232
          38353061643365626635613435376232323934616233343466623738393562333838663634323563
          37663330376337633562313665316164663039346137616333666437356263353433383330356665
          34396233653533666139346662373638663332393631396431333138343139356666306637356662
          65323637306430653735646233353735393237356361393838613232666635323936613835373866
          62303738343535376665636430313664396565393666346239306133353733383238353338623338
          34376234643537333533623134623838623266313935343332363364383261313332363737636537
          30636532356366306538326331663237613230663038666530323033353964613237336132363634
          38353466316137363135313432343764623966656234373765343062393061333962366233333838
          66636536396466366631316265616338326636323062396434316434353439313335623866636638
          34623364626539633262346431623932663664383733656331373133353532306639613466613030
          38386266383332663731653332666334643965356439313861653631356637653033633330616634
          65313561386538363566326165393564313964386539646339323135306662343762383637656466
          37643961353162343263373865616563376334663361616132616663623039333238313936316262
          35353763363961383233363238313332326532306535383837396534346364323366616237636664
          39623332643236366538363239303063623238626564633535316264373839383264623936343162
          65646135383466396663333362373862323031326231626132353230366261623161326461353138
          63306338393163386163643730313037313030373234313733613830336132313762646638663437
          39303334613364306662316238363238393036373562633361376166316663303235343734633537
          33643663353065646337323466333666333665316537616638633639323033636334323132613532
          65393362646264393736616233383061333837363831363161313439636566373936323938356561
          31336533646334383734316334656163643962323866653533393664306631353234306534303633
          31373531633030633366373632363766376636656432656462633764666432313736313638643430
          39373034316532613466316263316437386332633836303263333764326566643136303066613435
          32336336353033356163313164643161353537383132633736343234623166663166663662363264
          38643366326466343632343033333038306464373562646266383836633662336234356239346566
          34303133353734366364376565613635393633386139663836303034333138353964316538356433
          32373462343464613039353433636139353436646264663838343236306533343536623936386663
          31653765663237643639643436643962316462613565343834613634663633656339393061356466
          36343663313538353366303766326236626662373933326133666235343065653033613634353437
          32333436316533646630306661653062396430373665353561303765333739623336333237613638
          63326465363539333132616238346437303833373431316337373731646334336534393732613962
          66383262393465353339303933323835613330643333643031653039663735623466316630356339
          33316332666236346132643236316164333833613733353365623761386131326339353633303265
          64353534363538323865666466373630306137626464653030373231356234386134316466373534
          35333765323937373366326434653536646339393261343366323761376162376439363233306366
          34353030343937643937613964623062353936343130343162376663353765643235613831373931
          62383531333264623934356439653565626438653232666334323664633366306639646535393731
          64613337316566353839
Encryption successful